### ISSUE TITLE
Division by zero with \fscx0/\fscy0 (affects display if int = long)

### ISSUE THREAD

**Issue by wiiaboo** [libass/libass#185]
Using \fscx0 turns the following text in the same subtitle invisible until \fscx0 is used again, even with \fscx100 used right ~~away~~ after at least a character.

vsfilter:
![vsfilter](http://i.fsbn.eu/OanZ.png)

libass:
![libass](http://i.fsbn.eu/ifgv.png)

After making the images smaller I tried different combinations of {\fscx0} and space. It seems if there's no character between {\fscx0} and {\fscx100} this bug doesn't occur (since both tags cancel each other?).

1: `{\fscx0}{\fscx100}hidden{\fscx0}{\fscx100} text`
2: `{\fscx0}{\fscx100}hidden{\fscx0}d{\fscx100} text`
3: `{\fscx0} {\fscx100}hidden{\fscx0}{\fscx100} text`
4: `{\fscx0} {\fscx100}hidden{\fscx0} {\fscx100} text`
5: `{\fscx0.1} {\fscx100}hidden{\fscx0.1} {\fscx100} text`

**Comment by wiiaboo** [comment]
It also seems to depend on the number of characters between {\fscx0} and {\fscx100}.
![libass](http://i.fsbn.eu/k6dl.png)

6: `{\fscx0}abc{\fscx100}hidden{\fscx0}a{\fscx100} text`
7: `{\fscx0}ab{\fscx100}hidden{\fscx0}a{\fscx100} text`
8: `{\fscx0}ab{\fscx100}hidden{\fscx0}ab{\fscx100} text`

**Comment by astiob** [comment]
I’m positive I’ve seen this in my own tests a couple of years ago, but now I can’t reproduce this even in libass 0.12.0, which was released way before this issue was reported here. Can anyone?

Perhaps this was actually a bug in some other library that libass used and that bug is now fixed. Not sure how that could work, but then I have no idea how a libass bug could cause this either.

**Comment by wiiaboo** [comment]
Still happens here with libass master and latest releases of freetype and harfbuzz:
![blank mkv_0 280000](https://cloud.githubusercontent.com/assets/111605/13272001/dabbe734-da90-11e5-8ead-450187cdf39e.png)

**Comment by astiob** [comment]
Thanks. Could you post the whole script, just in case it’s related to the font or some other style component?

**Comment by wiiaboo** [comment]
[ASS file](http://sprunge.us/XEKF)
Tested with mpv master and test.exe as well.

**Comment by astiob** [comment]
Nope, I can’t reproduce it. I’ve tried enabling and disabling HarfBuzz, assembler code, the internal rasterizer and hinting; the problem never appears. I can always see “invisible text” in both lines. I’ve asked on IRC, and the response I’ve received so far has only confirmed my findings.

Are you perhaps building libass with any extra patches? You said “master”, so it doesn’t sound like it, but let’s double-check. I don’t know what else could be relevant. :(

**Comment by wiiaboo** [comment]
> Are you perhaps building libass with any extra patches?

I'm pretty sure I'm not.
You can see [the exact script](https://github.com/jb-alvarado/media-autobuild_suite/blob/master/build/media-suite_compile.sh) I use to build it and other stuff.

It didn't happen just to me since the original issue came from someone else complaining about Commie using \fscx0 in OreGaIru S2 or something and turning letters invisible until \fscx0 was used again. I don't have the original script and it's 404.

**Comment by astiob** [comment]
I’ve been able to reproduce and debug this in Windows, thanks.

The problem is actually simple. Shear (`\fax` and `\fay`) conceptually (and literally in VSFilter) takes effect before `\fscx` and `\fscy`, but we multiply everything by <var>fscx</var> and <var>fscy</var> very early and apply shear late. So when we finally do apply shear and whenever we need shear for correct baseline positioning, we take the shear coefficients to be `fay / fscx * fscy` and `fax / fscy * fscx`. If <var>fscx</var> or <var>fscy</var> is zero, we divide by zero!

For <var>fscy</var> this probably doesn’t matter much, but <var>fay</var>, and hence division by <var>fscx</var>, is used to compute the text baseline, so the division by zero affects the baseline. Specifically, we get a NaN or an infinity, each of which gives `LONG_MIN` when converted to `FT_Pos` (aka `long`). This makes the baseline suddenly jump by `LONG_MIN` subpixels for each glyph cluster that has <var>fscx</var>=0. Then, when `CombinedBitmapInfo` is created, positions are right-shifted by a few bits to get whole pixels and stored in `int` fields. So if `long` is longer than `int` like it is on AMD64 UNIX, the `LONG_MIN` term gets truncated to `0`, and everything just works as if nothing happened. On the other hand, if `long` is the same length as `int` like it is on Windows and on IA-32 UNIX, combined bitmap positions get a nonzero term of `INT_MIN >> 6` pixels, and the bitmaps disappear far off the top edge of the screen. But even then, every two `LONG_MIN` terms always add up to `0`, so after every other cluster with <var>fscx</var>=0, things go back to normal!

I say “just work” and “normal”, but actually this issue also means that nonzero shear doesn’t work correctly when the corresponding scale factor is zero.

Right now I can think of only two solutions:

1. Don’t immediately multiply everything by fscx and fscy and instead do it in `transform_3d_points` like VSFilter does. One downside is additional discretization errors. (?) (Currently we ask FreeType to scale by <var>fscx</var> and <var>fscy</var> _during_ the retrieval of glyph outlines; does it actually produce less errors than scaling later?) Oh, and this needs a rather large code audit. Anything else?
2. Just detect and skip anything with <var>fscx</var>=0 or <var>fscy</var>=0 right away. It’s not gonna be seen on screen anyway!

**Comment by wiiaboo** [comment]
I get that a second \fscx0 resets it back to normal but why does it work with an even number of characters?

**Comment by astiob** [comment]
The second `\fscx0` doesn’t actually do anything itself. The second _glyph cluster_ that has `\fscx0` restores it to normal. (A glyph cluster is roughly the same as character, but it includes the base glyph as well as all associated diacritical marks etc. Basically it’s what you’d call a character if you didn’t know how computers stored text.)

If you have several `\fscx0` clusters in a row, like in `{\fscx0}abcd{\fscx100}` (where each letter forms its own cluster), the first cluster breaks it, the second fixes, the third breaks, the fourth fixes again… so it appears as if it’s broken if and only if you have an even number of clusters. But if you have some non-`\fscx0` text after an odd number of `\fscx0` clusters, like in `{\fscx0}a{\fscx100} quick brown fox{\fscx0}!`, then it stays broken until it gets fixed by the next `\fscx0` cluster, in this case the exclamation mark.

The technical reason it works like this is that each cluster has an “advance” value that specifies its position on screen relative to the previous cluster, so that text can be laid out in a line. The “baseline” on which the base of all glyphs in the line rests is implicitly specified by these advance values. Since the baseline needs to be affected by `\fay`, libass updates the cluster advances to incorporate shear, and like I explained before, it ends up adding `LONG_MIN` to the vertical advance value of each cluster that has `\fscx0`. Therefore each such cluster moves by `LONG_MIN` vertically, and since the advances are relative to the previous cluster, all subsequent clusters move along with it. But the second cluster to do this has now added `2 * LONG_MIN` to the original baseline, but this overflows to 0, bringing the position back to normal.

(It might actually be the second printable Unicode character rather than glyph cluster if HarfBuzz is disabled and/or if `\fsp` is nonzero. The code would still think it’s glyph clusters, but only HarfBuzz knows how to build clusters from characters correctly.)

Did this explanation make it any clearer?

**Comment by wiiaboo** [comment]
Yes, and I understand the two solutions above better now. Thanks.

**Comment by rcombs** [comment]
Looks like this now happens on 64-bit UNIX systems as well, probably because we switched from FT types to internal ones and some things that used to be `long` are now `int`.
